baseURL: https://www.mariehmai.me/
languageCode: en-us
defaultContentLanguage: en
title: Marie-Hélène Mai - Full Stack Software Engineer
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  side-projects: /:contentbasename/

imaging:
  quality: 99

params:
  # description: Marie-Hélène Mai, Full Stack Software Engineer.
  # homeMetaContent: My personal website using Hugo theme.
  footer: © 2015-2025 Marie-Hélène Mai
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: true
  # navTitleText: Marie-Hélène Mai
  logoAlt: An alternative text description of the logo
  customCss:
    - css/global.css
    - css/icons.css
  customJs:
    - js/type_writer.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    # - name: Side Projects
    #   url: /side-projects/
    #   weight: 2
    # - name: Tags
    #   url: /tags/
    #   weight: 3

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
